name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push 2.0.0
      id: docker_build_2_0_0
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./ruby-2.0.0.Dockerfile
        push: true
        tags: facundofarias/deploybot-ruby-2.0.0:0.1

    - name: Image digest 2.0.0
      run: echo ${{ steps.docker_build_2_0_0.outputs.digest }}

    - name: Build and push 2.3.7
      id: docker_build_2_3_7
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./ruby-2.3.7.Dockerfile
        push: true
        tags: facundofarias/deploybot-ruby-2.3.7:0.1

    - name: Image digest 2.3.7
      run: echo ${{ steps.docker_build_2_3_7.outputs.digest }}

    - name: Build and push 2.7.6
      id: docker_build_2_7_6
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./ruby-2.7.6.Dockerfile
        push: true
        tags: facundofarias/deploybot-ruby-2.7.6:0.1

    - name: Image digest 2.7.6
      run: echo ${{ steps.docker_build_2_7_6.outputs.digest }}